FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY server/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server code
COPY server/ .

# Expose port
EXPOSE 3000

# Command to run the app
CMD ["npm", "run", "dev"]
