FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the client code
COPY client/ .

# Expose port
EXPOSE 5173

# Command to run the app
CMD ["npm", "run", "dev"]
